### ISSUE TITLE
URGENT - Migration is not working - Please Assist

### ISSUE THREAD

**Issue by yamap562** [rmeissner/safe-migrator#3]
URGENT HELP. I've been using your BSC MIGRATOR for the past year without any issues. I haven't used it in over 6 months or so.
I have 4 wallets hard code into a smart contract from which i cannot withdraw the bnb without your migrator.
At my surprise last Saturday your migrator did not work.
We set the fall back handler and executed the BSC fix with the native transaction builder.
We can't tell if it did anything, but the transaction was successful. However it's still not letting us withdraw from the contract.
These are our 4 hard coded wallets :
bnb:0xb629e9b3167c769b0044b67c67bc7fb36CDcE131
bnb:0xee6CB396286E79648b0EadDbBaFA68C38cD70f29
bnb:0x302bE2dABe3f55eF098e80a670F55Bcd1145Fd05
bnb:0x2c5967e124fc99B7e9E04Ba075Cd80fEc0AD55cb
Contract Address for the NFT collection:
0x458AEE8b453F0d0FF22D8aab4FC1D10026a62068
I believe it stopped working since perhaps your new implementation. I haven't done it in 250 days.

**Comment by rmeissner** [comment]
This is most likely related to the deprecation of the service url (https://github.com/rmeissner/safe-migrator/blob/main/src/logic/constants.ts#L19). I will update them and push an update, then you can test it.

**Comment by rmeissner** [comment]
Updated with e9f2c197445e5cec61fe8bdca11a3069bee74765 
let me know if this worked

**Comment by yamap562** [comment]
Thank you Richard for getting back to us. 
We have executed the transaction for migration for all the 4 concerning gnosis safe wallets. 
bnb:0xb629e9b3167c769b0044b67c67bc7fb36CDcE131
bnb:0xee6CB396286E79648b0EadDbBaFA68C38cD70f29
bnb:0x302bE2dABe3f55eF098e80a670F55Bcd1145Fd05
bnb:0x2c5967e124fc99B7e9E04Ba075Cd80fEc0AD55cb

This is the transaction hash of the respective tx:
0x9bc8c128d2e55ad14c24c88fe31ea1cbc7167aefda03e7c6f08e6236fdc60f24
0x47b0b901d6785847865a9c345a3b84413f0396f0f4d74fbfb9c47e82033fdc6f
0x988b02748c31759885146acdd478009f6ed516f7ac1f7442a6499d1154d7ce1a
0x3775ff9b42aea2db6b6a125047c6a93564688f6610d0f7fefd94ca8c175e1187

Following that i tried to do the withdrawal but it failed:
https://bscscan.com/tx/0x2967cfd7cbfc3cad8e0cc5095762f72ba7509529e8188c19dd493b13b2d7c700

We also tried to manually increase the gas/gwei to 3M (on a second attempt to withdraw) and we got below :
Transaction has been reverted by the EVM: { "type": "0x2", "from": "0x2a91bc1c9f25bb3ecaed04bb4967e853b2899a21", "to": "0x458aee8b453f0d0ff22d8aab4fc1d10026a62068", "status": false, "cumulativeGasUsed": 7476808, "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "transactionHash": "0x02cb0c514ce9b0b33030e46406830464ce1b1e8adbd11376ba66df8edd54a5df", "contractAddress": null, "gasUsed": 35327, "blockHash": "0x1ed2ab3bc708f9f2c5567125e4962b5557c05946f2f3ee095ac1d0fe5c274d25", "blockNumber": 31477542, "transactionIndex": 87, "effectiveGasPrice": "0xb2d05e00", "events": {} }

Our Gnosis Safe of those 4 wallets are also not loading FYI. since the execution of those tx/ns
It tried to reload/refresh but still doesn't load properly. 

Once again please note this an urgent matter where 20'000$+ is stuck in the contract 
this is for the community and our protocol.

**Comment by rmeissner** [comment]
So after some research I found the following:
- EIP-2929 and EIP-2930 have been activated on BNC (see https://github.com/bnb-chain/bsc/pull/1608), this means that even the migrated version will not work. There are workaround for this and they are listed [here](https://help.safe.global/en/articles/40813-why-can-t-i-transfer-eth-from-a-contract-into-a-safe)

I would recommend to revert the migration and follow the process outlined in the help center article.
